/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuisPertemuan4GajiKaryawan;

/**
 *
 * @author Hendri Gunawan - 41815120093
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemKaryawanTetap = new javax.swing.JMenuItem();
        menuItemKaryawanHonorer = new javax.swing.JMenuItem();
        menuProperty = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Author: Hendri Gunawan");

        jMenu1.setText("Gaji");

        menuItemKaryawanTetap.setText("Karyawan Tetap");
        menuItemKaryawanTetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKaryawanTetapActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemKaryawanTetap);

        menuItemKaryawanHonorer.setText("Karyawan Honorer");
        menuItemKaryawanHonorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKaryawanHonorerActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemKaryawanHonorer);

        jMenuBar1.add(jMenu1);

        menuProperty.setText("Property");
        menuProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPropertyActionPerformed(evt);
            }
        });

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuProperty.add(menuItemExit);

        jMenuBar1.add(menuProperty);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPropertyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPropertyActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemKaryawanTetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKaryawanTetapActionPerformed
        // TODO add your handling code here:
        GajiKaryawanTetap gajiKaryawanTetap = new GajiKaryawanTetap();
        gajiKaryawanTetap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemKaryawanTetapActionPerformed

    private void menuItemKaryawanHonorerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKaryawanHonorerActionPerformed
        // TODO add your handling code here:
        GajiKaryawanHonorer gajiKaryawanHonorer = new GajiKaryawanHonorer();
        gajiKaryawanHonorer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemKaryawanHonorerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemKaryawanHonorer;
    private javax.swing.JMenuItem menuItemKaryawanTetap;
    private javax.swing.JMenu menuProperty;
    // End of variables declaration//GEN-END:variables
}
