/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.soal2;

/**
 *
 * @author Hendri Gunawan - 41815120093
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOperasiPerhitungan = new javax.swing.JMenu();
        menuItemSegitiga = new javax.swing.JMenuItem();
        menuItemPersegiPanjang = new javax.swing.JMenuItem();
        menuItemLingkaran = new javax.swing.JMenuItem();
        menuPilihan = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuOperasiPerhitungan.setText("Operasi Perhitungan");

        menuItemSegitiga.setText("Segitiga");
        menuItemSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSegitigaActionPerformed(evt);
            }
        });
        menuOperasiPerhitungan.add(menuItemSegitiga);

        menuItemPersegiPanjang.setText("Persegi Panjang");
        menuItemPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPersegiPanjangActionPerformed(evt);
            }
        });
        menuOperasiPerhitungan.add(menuItemPersegiPanjang);

        menuItemLingkaran.setText("Lingkaran");
        menuItemLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLingkaranActionPerformed(evt);
            }
        });
        menuOperasiPerhitungan.add(menuItemLingkaran);

        jMenuBar1.add(menuOperasiPerhitungan);

        menuPilihan.setText("Pilihan");

        menuItemExit.setText("Keluar");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuPilihan.add(menuItemExit);

        jMenuBar1.add(menuPilihan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSegitigaActionPerformed
        // TODO add your handling code here:
        Segitiga segitiga = new Segitiga();
        segitiga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemSegitigaActionPerformed

    private void menuItemPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPersegiPanjangActionPerformed
        // TODO add your handling code here:
        PersegiPanjang persegiPanjang = new PersegiPanjang();
        persegiPanjang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemPersegiPanjangActionPerformed

    private void menuItemLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLingkaranActionPerformed
        // TODO add your handling code here:
        Lingkaran lingkaran = new Lingkaran();
        lingkaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLingkaran;
    private javax.swing.JMenuItem menuItemPersegiPanjang;
    private javax.swing.JMenuItem menuItemSegitiga;
    private javax.swing.JMenu menuOperasiPerhitungan;
    private javax.swing.JMenu menuPilihan;
    // End of variables declaration//GEN-END:variables
}
